//==============================================================================
// Hierarchical dofile generated by Conformal LEC
// Version: 20.10-p100 (01-May-2020) (64 bit executable)
//------------------------------------------------------------------------------
// The command 'set module property' sets the instance context for the current
// root module. It is intended only for hierarchical comparison, and should
// not be modified by the user.
//==============================================================================

set system mode setup
// Comparing module 'AES_inverse_gf_mydesign_1'
set root module AES_inverse_gf_mydesign_1 -Golden
set root module AES_inverse_gf_mydesign_1 -Revised
set module property -instance /U_AES_MSB/U_AES_decrypt/U_AES_inverse_gf -Golden
set module property -instance /U_AES_MSB/U_AES_decrypt/U_AES_inverse_gf -Revised
report black box -NOHidden
set system mode lec
analyze multiplier -cdp_info; analyze datapath -merge -share -effort medium -verbose
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
add black box AES_inverse_gf_mydesign_1 -module -hier -Golden
add black box AES_inverse_gf_mydesign_1 -module -hier -Revised
// Comparing module 'AES_inverse_gf_mydesign_0'
set root module AES_inverse_gf_mydesign_0 -Golden
set root module AES_inverse_gf_mydesign_0 -Revised
set module property -instance /U_AES_LSB/U_AES_decrypt/U_AES_inverse_gf -Golden
set module property -instance /U_AES_LSB/U_AES_decrypt/U_AES_inverse_gf -Revised
report black box -NOHidden
set system mode lec
analyze multiplier -cdp_info; analyze datapath -merge -share -effort medium -verbose
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
add black box AES_inverse_gf_mydesign_0 -module -hier -Golden
add black box AES_inverse_gf_mydesign_0 -module -hier -Revised
// Root modules
// Comparing module 'top'
set root module top -Golden
set root module top -Revised
set module property -instance / -Golden
set module property -instance / -Revised
report black box -NOHidden
set system mode lec
analyze multiplier -cdp_info; analyze datapath -merge -share -effort medium -verbose
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
report hier_compare result
report hier_compare result -Non_equivalent
report hier_compare result -Abort
report hier_compare result -Uncompared
// _END_OF_LEC_HIERARCHICAL_DOFILE_
