# testbench
test_all.v

# netlist generated by Design Compiler
../syn/netlist/top_syn.v
sram_model/sram_2048x64b.v
sram_model/sram_32x8b.v

# Logic Gate models
-v /usr/cadtool/GPDK45/gsclib045_svt_v4.4/gsclib045/verilog/slow_vdd1v2_basicCells.v

+define+GATESIM
+define+PAT_L=1+PAT_U=7
+define+TEST_EN
+access+r
